plugins {
  id 'org.springframework.boot'
  id "io.spring.dependency-management"
}

group = 'dr.sbs'
// version should not have '-'
version = new Date().format("yyyy.MMdd.HHmm", TimeZone.getTimeZone("GMT+08:00"))
archivesBaseName = 'sbs-front'
sourceCompatibility = 17
description = 'Spring Boot Starter Front Application.'

mainClassName = 'dr.sbs.front.App'

jar {
  enabled = false // 不生成 xxx-plain.jar
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-security:3.5.11'
  implementation 'org.springframework.session:spring-session-data-redis:2.7.4'
  implementation 'org.springframework.boot:spring-boot-starter-data-redis:3.5.11'
  implementation 'org.springframework.boot:spring-boot-starter-websocket:3.5.11'

  // projects
  implementation project(':pro-mp')
  implementation project(':pro-common')
}
